version: '3.3'

services:

  minio:
    container_name: minio
    image: "minio/minio:latest"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
      MINIO_USERNAME: "root"
      MINIO_GROUPNAME: "root"
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    command: "server /data"

  spark-master:
    container_name: spark-master
    image: "gemelen/spark:2.4.3-2.12-2.8.5"
    command: "/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    container_name: spark-worker
    image: "gemelen/spark:2.4.3-2.12-2.8.5"
    command: "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master:7077"
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  nifi:
    container_name: nifi
    image: apache/nifi:latest
    ports:
      - "8082:8080"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  top-songs-2:
    container_name: top-songs-2
    image: "top-songs-2:latest"
    environment:
      - MASTER=spark://spark-master:7077
    volumes:
      - ./minio/data:/minio/data
    depends_on:
      - minio
      - spark-worker
